/* PropDesk knowledge base — firm profiles, FAQs, support inboxes, escalation rules.
   Facts are synthesized from publicly documented 2025–2026 program patterns.
   Always treat a firm's own current rulebook as source of truth. */

window.PROPDESK_KB = {
  version: "2026.09",
  disclaimer:
    "Answers are based on publicly documented program patterns. Rulebooks change. Confirm critical details in your firm's current terms.",

  firms: {
    ftmo: {
      id: "ftmo", name: "FTMO", short: "FTMO", color: "#17c37b",
      supportEmail: "support@ftmo.com", portal: "https://ftmo.com",
      models: ["2-step Challenge + Verification"],
      platforms: ["MT4", "MT5", "cTrader", "DXtrade"],
      profitSplit: "80% standard, up to 90%",
      payoutCycle: "On demand after the payout window; commonly processed in 1–2 business days after approval",
      payoutSlaDays: 2, maxAccount: "$400,000",
      drawdown: "Typically 5% daily / 10% max (static on many account types)",
      consistency: "No classic funded consistency cap on standard FTMO Account; challenge has trading-objective rules",
      news: "News trading allowed on funded accounts with restrictions on some products around high-impact releases",
      ea: "EAs generally allowed if they are not prohibited strategies (HFT tick scalping, arbitrage, martingale/grid as defined in terms)",
      kyc: "KYC required before first payout",
      notes: "Longest documented forex/CFD payout history among major evaluation firms. US clients generally not accepted.",
    },
    fundednext: {
      id: "fundednext", name: "FundedNext", short: "FundedNext", color: "#3b82f6",
      supportEmail: "support@fundednext.com", portal: "https://fundednext.com",
      models: ["Stellar 1-Step", "Stellar 2-Step", "Stellar Lite", "Stellar Instant"],
      platforms: ["MT4", "MT5", "cTrader", "Match-Trader"],
      profitSplit: "Up to ~90–95% depending on model and add-ons",
      payoutCycle: "Often advertised 24-hour processing after approval on eligible models",
      payoutSlaDays: 1, maxAccount: "$200,000 CFD (higher on some futures products)",
      drawdown: "Varies by model — check daily loss and max loss on the exact plan",
      consistency: "Some models apply a consistency / best-day share rule on payouts",
      news: "News trading policy is model-specific; Instant / some Stellar plans are more flexible than others",
      ea: "EAs usually allowed except banned strategy classes",
      kyc: "Identity verification required before payouts",
      notes: "Multiple evaluation models. Challenge-phase profit share exists on some products. Confirm the exact plan you bought.",
    },
    the5ers: {
      id: "the5ers", name: "The5ers", short: "The5ers", color: "#f59e0b",
      supportEmail: "info@the5ers.com", portal: "https://the5ers.com",
      models: ["High Stakes", "Hyper Growth", "Bootcamp"],
      platforms: ["MT5"],
      profitSplit: "Scales; High Stakes can reach up to 100% after milestones",
      payoutCycle: "Bi-weekly on many programs after first cycle",
      payoutSlaDays: 5, maxAccount: "Scaling path well above $1M on some programs",
      drawdown: "Program-specific; High Stakes uses defined daily/max loss bands",
      consistency: "Program-specific; Hyper Growth emphasizes target + risk, not a classic 30% day rule",
      news: "Generally more permissive than two-step CFD firms — confirm program PDF",
      ea: "Allowed within strategy restrictions", kyc: "Required for withdrawals",
      notes: "Known for long scaling track and higher lifetime caps.",
    },
    fundingpips: {
      id: "fundingpips", name: "FundingPips", short: "FundingPips", color: "#22c55e",
      supportEmail: "support@fundingpips.com", portal: "https://fundingpips.com",
      models: ["1-Step", "2-Step", "Zero / instant-style products when offered"],
      platforms: ["MT5", "cTrader", "Match-Trader", "TradeLocker"],
      profitSplit: "Often 80% base, scaling toward 90–100% on some ranks",
      payoutCycle: "Weekly on many plans; some advertised within 24 hours after approval",
      payoutSlaDays: 2, maxAccount: "Up to $100k–$500k depending on product line",
      drawdown: "Daily and max loss vary by step model",
      consistency: "Payout consistency rules appear on some account types — read the plan card",
      news: "Model-specific", ea: "Allowed with banned-strategy list", kyc: "Required before first payout",
      notes: "Popular one-step option. Rules differ sharply between 1-step and 2-step — pick the exact product.",
    },
    e8: {
      id: "e8", name: "E8 Markets", short: "E8", color: "#a855f7",
      supportEmail: "support@e8markets.com", portal: "https://e8markets.com",
      models: ["E8 Evaluation", "E8 One", "E8 Track"],
      platforms: ["MT5", "Match-Trader", "TradeLocker"],
      profitSplit: "Up to 100% on some configurations",
      payoutCycle: "On-demand / frequent cycles after eligibility",
      payoutSlaDays: 3, maxAccount: "Typically up to $200k–$400k evaluation notionals",
      drawdown: "EOD / intraday definitions differ by account — this is a frequent dispute point",
      consistency: "Present on some payout paths",
      news: "More permissive than FTMO on several products",
      ea: "Allowed except prohibited classes", kyc: "Required",
      notes: "Watch whether drawdown is balance-based, equity-based, or end-of-day. Screenshot the dashboard definition.",
    },
    goat: {
      id: "goat", name: "Goat Funded Trader", short: "Goat", color: "#eab308",
      supportEmail: "support@goatfundedtrader.com", portal: "https://goatfundedtrader.com",
      models: ["2-Step", "1-Step"],
      platforms: ["MT5", "cTrader", "Match-Trader", "TradeLocker"],
      profitSplit: "Up to 80–100% depending on add-ons",
      payoutCycle: "Frequent; confirm current SLA in dashboard",
      payoutSlaDays: 3, maxAccount: "Up to $200k typical",
      drawdown: "Plan-specific daily + max", consistency: "Often present",
      news: "Generally allowed on many Goat plans", ea: "Allowed with restrictions", kyc: "Required",
      notes: "News-friendly positioning. Still screenshot the exact plan rules you purchased.",
    },
    acg: {
      id: "acg", name: "Alpha Capital Group", short: "ACG", color: "#38bdf8",
      supportEmail: "support@alphacapitalgroup.uk", portal: "https://alphacapitalgroup.uk",
      models: ["1-Step", "2-Step"],
      platforms: ["MT4", "MT5", "cTrader", "DXtrade"],
      profitSplit: "Up to 80–90%", payoutCycle: "Bi-weekly common",
      payoutSlaDays: 5, maxAccount: "Up to $200k typical",
      drawdown: "Daily + max, static on many plans", consistency: "Check plan PDF",
      news: "Restricted around selected high-impact events on some accounts",
      ea: "Allowed within terms", kyc: "Required",
      notes: "UK-facing brand. Confirm restricted-country list before buying.",
    },
    apex: {
      id: "apex", name: "Apex Trader Funding", short: "Apex", color: "#f97316",
      supportEmail: "support@apextraderfunding.com", portal: "https://apextraderfunding.com",
      models: ["Futures evaluation → PA account"],
      platforms: ["NinjaTrader", "Tradovate", "Rithmic", "TradingView bridges"],
      profitSplit: "100% of first $25k then 90% on many plans (confirm current promo)",
      payoutCycle: "After consistency / threshold rules; processing often several business days via Rise",
      payoutSlaDays: 8, maxAccount: "Multiple accounts; contract caps by size",
      drawdown: "Trailing threshold / EOD trailing depending on account generation",
      consistency: "Payout consistency / 5 winning days style rules are common in futures props",
      news: "News trading usually allowed in futures props; flat-by-close and contract-size rules matter more",
      ea: "Autos and copy tools restricted — read Apex policy",
      kyc: "Required + payout provider onboarding (often Rise)",
      notes: "Futures, not forex. Most disputes are trailing drawdown, consistency days, and contract-limit breaches.",
    },
    topstep: {
      id: "topstep", name: "Topstep", short: "Topstep", color: "#ef4444",
      supportEmail: "support@topstep.com", portal: "https://www.topstep.com",
      models: ["Trading Combine → Funded Account"],
      platforms: ["TopstepX", "Tradovate", "NinjaTrader", "others via connection"],
      profitSplit: "100% of first $5k–$10k then 90% typical (plan-dependent)",
      payoutCycle: "Weekly via their payout partner after consistency rules",
      payoutSlaDays: 5, maxAccount: "$150k Combine sizes common",
      drawdown: "Maximum Loss Limit / trailing logic — live number is on the dashboard",
      consistency: "Yes — payouts require consistency days and often a winning-day count",
      news: "Allowed; risk of gap through MLL is on the trader",
      ea: "Automation policy is strict — do not assume bots are fine", kyc: "Required",
      notes: "Futures Combine model. Breaches are usually MLL, scaling plan contract limits, or flatting rules.",
    },
    instant: {
      id: "instant", name: "Instant Funding", short: "Instant Funding", color: "#14b8a6",
      supportEmail: "support@instantfunding.io", portal: "https://instantfunding.io",
      models: ["Instant funded (no evaluation) + evaluation hybrids"],
      platforms: ["MT5", "cTrader", "Match-Trader"],
      profitSplit: "Up to 90%+",
      payoutCycle: "Frequent / on-demand after min days and profit",
      payoutSlaDays: 3, maxAccount: "Plan-dependent, often $10k–$100k instant notionals",
      drawdown: "Tighter than two-step firms on many instant books",
      consistency: "Common on instant books", news: "Often allowed — still confirm",
      ea: "Restricted classes apply", kyc: "Required before payout",
      notes: "You pay for skipping the challenge. Instant books usually have stricter consistency and payout caps early on.",
    },
  },

  topics: [
    { id: "profit-target", tags: ["profit target", "target", "pass challenge", "how much profit", "phase 1", "phase 2", "verification"], title: "Profit target",
      answer: (f) => `On ${f.name}, profit targets are product-specific (often ~8–10% on a first evaluation step and ~5% on a verification step, or a single target on 1-step / instant books).\n\nOpen your dashboard → account card and read the exact target for the plan you paid for. Marketing pages and the live account card can differ after a promo.\n\nIf you are close to the target, do not increase size to “finish today.” Daily loss limits are how most near-pass accounts die.` },
    { id: "daily-dd", tags: ["daily drawdown", "daily loss", "dll", "daily limit", "hit daily", "5%", "daily dd"], title: "Daily drawdown",
      answer: (f) => `${f.name} daily loss: ${f.drawdown}.\n\nCritical distinction most traders miss:\n• Equity-based daily loss counts floating P&L.\n• Balance-based / EOD daily loss may ignore open trades until they close or until end of day.\n\nIf you think the firm calculated daily loss wrong, we need: (1) screenshot of the rule definition on your dashboard, (2) account statement with timestamps in server time, (3) the exact equity/balance at the alleged breach. Without those three, support will close the ticket as “trader error.”` },
    { id: "max-dd", tags: ["max drawdown", "maximum loss", "mll", "trailing", "threshold", "static drawdown", "relative drawdown"], title: "Maximum / trailing drawdown",
      answer: (f) => `Max loss on ${f.name}: ${f.drawdown}.\n\nTrailing / threshold accounts move the floor up as you make new highs (common on futures: Apex, Topstep). Static max loss stays fixed from starting balance (common on many FX evaluations).\n\nIf your account used trailing logic and you thought it was static, that is almost never “firm fault” — it is a rulebook mismatch. It becomes a case only if the dashboard showed one definition and the breach used another.` },
    { id: "consistency", tags: ["consistency", "best day", "30%", "40%", "lot consistency", "payout denied consistency", "uneven profits"], title: "Consistency rule",
      answer: (f) => `${f.name} consistency: ${f.consistency}.\n\nA consistency rule usually means no single day (sometimes no single trade) may exceed a set % of total closed profit when you request a payout. It is the #1 reason funded payouts get parked, not denied forever.\n\nFix path: keep trading eligible days until the best day falls under the cap, then resubmit. Attach the payout denial text plus a daily-PnL breakdown. If the firm applied a % that is not in your signed terms, that can be escalated.` },
    { id: "payout", tags: ["payout", "withdraw", "withdrawal", "payment", "haven't been paid", "pending payout", "riseworks", "wise", "crypto payout"], title: "Payout process",
      answer: (f) => `${f.name} payouts: ${f.payoutCycle}. Profit split: ${f.profitSplit}. KYC: ${f.kyc}.\n\nChecklist before you assume the firm is stalling:\n1. KYC approved and name matches the payout method.\n2. Contract / trader agreement signed.\n3. Payout method added (bank / Wise / Rise / crypto) and eligible in your country.\n4. You met min trading days and any consistency / first-payout cap.\n5. No open positions or pending orders if the firm requires a flat book.\n6. The request is actually in “approved” not “under review.”\n\nClock usually starts at approval, not at click. If approved more than ${f.payoutSlaDays} business days ago with no funds and no written reason, we can compile a case.` },
    { id: "payout-denied", tags: ["payout denied", "denied withdrawal", "rejected payout", "won't pay", "refused payout"], title: "Payout denied",
      answer: (f) => `A denial is only automatically “firm fault” if they cite a rule that is not in the terms you agreed, apply a rule retroactively, or ignore their own published SLA after approval.\n\nMost denials are: consistency, min days, incomplete KYC, prohibited strategy flag, news-window breach, or an early-payout cap.\n\nSend me:\n• Exact denial wording (screenshot)\n• Account login / ID\n• Plan name and purchase date\n• Daily profit breakdown\n• The clause you believe they used vs the clause in your PDF\n\nI will tell you whether this is fixable on your side or ready to email ${f.supportEmail}.` },
    { id: "news", tags: ["news trading", "nfp", "fomc", "cpi", "red folder", "high impact", "news restriction"], title: "News trading",
      answer: (f) => `${f.name} news policy: ${f.news}.\n\nRestricted windows (when they exist) usually cover a few minutes before and after NFP, FOMC, CPI, and similar tier-1 releases. A market order that fills inside the window counts even if you clicked before it.\n\nIf you were breached for news and your plan page said news is allowed, attach both the plan marketing/rules PDF and the breach email. That mismatch is escalatable.` },
    { id: "ea", tags: ["ea", "expert advisor", "bot", "algo", "copy trading", "trade copier", "hft", "martingale", "grid"], title: "EAs and bots",
      answer: (f) => `${f.name}: ${f.ea}.\n\nAlmost every CFD firm bans some mix of: latency arbitrage, tick HFT, hedge across accounts, martingale/grid as they define it, and unmanaged copy trading from signal rooms.\n\nUsing a trade copier onto multiple funded accounts at the same firm is one of the fastest ways to get a payout frozen. If they flagged “copy trading” and you have unique entries, we need raw deal tickets with timestamps — not a strategy story.` },
    { id: "breach", tags: ["breached", "failed", "account closed", "blown", "hit limit", "soft breach", "hard breach"], title: "Account breach",
      answer: (f) => `A rule breach on ${f.name} normally ends that account. Entry fees are typically not refunded. Many firms sell a discounted reset rather than a refund.\n\nSoft-breach style products (if your plan has them) may close trades but leave the account alive. Hard breach closes it.\n\nI can only push the firm if:\n• Platform outage / reject / stop-out error is timestamped, or\n• Their dashboard number does not match the statement, or\n• They applied a rule that was not in force when you bought the account.\n\nUpload the breach notice + statement. If this is a normal daily-loss hit, the honest answer is: the account is done, look at reset cost vs a new challenge.` },
    { id: "kyc", tags: ["kyc", "verification", "id", "passport", "proof of address", "identity"], title: "KYC / verification",
      answer: (f) => `${f.kyc} at ${f.name}.\n\nPayouts will not move while KYC is pending. Common fails: cropped document edges, glare, name mismatch with the payout wallet/bank, expired ID, PoA older than 3 months, VPN during upload.\n\nThis is almost never a firm-fault case. Finish KYC, then re-check payout status. If KYC has been “pending review” for more than 7 business days with documents accepted on-screen, we can nudge them.` },
    { id: "platform", tags: ["platform", "mt4", "mt5", "ctrader", "dxtrade", "matchtrader", "tradelocker", "can't login", "server down", "requote", "slippage", "stop out"], title: "Platform / execution",
      answer: (f) => `${f.name} platforms: ${f.platforms.join(", ")}.\n\nPlatform blame needs evidence the firm can actually act on:\n• Exact server time of the incident\n• Symbol, ticket IDs, screenshots of rejects / disconnects\n• Whether you could trade the same symbol at a retail broker at that second (proves it was not a global holiday/halt)\n\nSlippage around news is not firm fault. A stop that never triggered while price traded through it on their own chart can be. Save the journal and the tick chart if you have it.` },
    { id: "reset", tags: ["reset", "retry", "restart account", "free retry", "discounted reset"], title: "Resets",
      answer: (f) => `Resets on ${f.name} are a commercial product, not a right. Some promotions include a free retry; most do not after a hard breach.\n\nAsk me for the current reset path only after you paste the exact plan name. I will not invent a free retry that the dashboard does not show — that creates false hope and angry tickets.` },
    { id: "scaling", tags: ["scale", "scaling", "increase account", "bigger account"], title: "Scaling",
      answer: (f) => `${f.name} max advertised path: ${f.maxAccount}. Scaling is earned after funded payouts or profit milestones, never during a failed challenge.\n\nIf a scale-up was promised in writing (email/dashboard) and not applied after you met the printed conditions, that is a clean case.` },
    { id: "restricted", tags: ["us client", "united states", "restricted country", "not available", "banned country"], title: "Restricted countries",
      answer: (f) => `Most forex/CFD props (including ${f.name} if they are a CFD book) restrict US residents and a short list of sanctioned or high-risk jurisdictions. Futures props (Apex, Topstep) often do accept US traders.\n\nIf you paid from a restricted country and the firm keeps the fee without issuing an account, request a refund citing the geo-block. That is usually refundable if they never issued credentials.` },
    { id: "refund", tags: ["refund", "chargeback", "money back", "cancel challenge"], title: "Refunds",
      answer: (f) => `${f.name} challenge fees are generally non-refundable once credentials are issued. Exceptions that sometimes work: double charge, payment taken but no account created, geo-restriction after payment, or a documented outage that made the product unusable from minute one.\n\nChargebacks after you traded the account usually get the profile banned across brands that share risk vendors. Prefer a written refund request first.` },
    { id: "min-days", tags: ["minimum trading days", "min days", "trading days", "too early payout"], title: "Minimum trading days",
      answer: (f) => `Many ${f.name} plans require a minimum number of trading days before a payout or before passing. A day usually counts only if you opened (sometimes closed) a position that day — check the definition.\n\nIf you requested a payout early, the fix is wait and resubmit. Not a firm-fault case.` },
    { id: "weekend", tags: ["weekend holding", "overnight", "swap", "hold over weekend"], title: "Overnight / weekend",
      answer: (f) => `Some ${f.name} plans forbid weekend holding or charge swap. A Friday position left open into Saturday on a no-weekend book is a breach even if Monday gaps in your favor.\n\nIf the plan PDF allows weekend holding and they breached you for it, escalate with the PDF highlight + the breach mail.` },
  ],

  escalateSignals: [
    "platform outage", "server down", "couldn't close", "couldn't open", "stop did not trigger",
    "wrong drawdown", "miscalculated", "not in the terms", "rule they invented", "retroactive",
    "payout approved", "still not paid", "delayed payout", "missing payout", "double charged",
    "charged twice", "no account after payment", "dashboard shows different", "they changed the rules",
    "sla missed", "ticket ignored", "no response", "execution error", "requotes freeze",
    "logged me out", "breach during outage",
  ],

  notFirmFaultSignals: [
    "i hit daily", "i went over", "revenge trade", "i averaged down", "martingale",
    "i held news", "i forgot kyc", "i requested too early", "my best day was",
    "i used a copier", "signal group",
  ],
};
