/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FirmsRouteImport } from './routes/firms'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as FirmFirmIdRouteImport } from './routes/firm.$firmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmsRoute = FirmsRouteImport.update({
  id: '/firms',
  path: '/firms',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmFirmIdRoute = FirmFirmIdRouteImport.update({
  id: '/firm/$firmId',
  path: '/firm/$firmId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/payouts': typeof PayoutsRoute
  '/rules': typeof RulesRoute
  '/firm/$firmId': typeof FirmFirmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/payouts': typeof PayoutsRoute
  '/rules': typeof RulesRoute
  '/firm/$firmId': typeof FirmFirmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/compare': typeof CompareRoute
  '/desk': typeof DeskRoute
  '/firms': typeof FirmsRoute
  '/payouts': typeof PayoutsRoute
  '/rules': typeof RulesRoute
  '/firm/$firmId': typeof FirmFirmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/compare'
    | '/desk'
    | '/firms'
    | '/payouts'
    | '/rules'
    | '/firm/$firmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/compare'
    | '/desk'
    | '/firms'
    | '/payouts'
    | '/rules'
    | '/firm/$firmId'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/compare'
    | '/desk'
    | '/firms'
    | '/payouts'
    | '/rules'
    | '/firm/$firmId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  CompareRoute: typeof CompareRoute
  DeskRoute: typeof DeskRoute
  FirmsRoute: typeof FirmsRoute
  PayoutsRoute: typeof PayoutsRoute
  RulesRoute: typeof RulesRoute
  FirmFirmIdRoute: typeof FirmFirmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firms': {
      id: '/firms'
      path: '/firms'
      fullPath: '/firms'
      preLoaderRoute: typeof FirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firm/$firmId': {
      id: '/firm/$firmId'
      path: '/firm/$firmId'
      fullPath: '/firm/$firmId'
      preLoaderRoute: typeof FirmFirmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  CompareRoute: CompareRoute,
  DeskRoute: DeskRoute,
  FirmsRoute: FirmsRoute,
  PayoutsRoute: PayoutsRoute,
  RulesRoute: RulesRoute,
  FirmFirmIdRoute: FirmFirmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
